version: '3.3'
services:
  server:
    image: "grpc-server"
    # build:
    #     context: .
    #     dockerfile: Dockerfile
    #     args:
    #         service: server
    ports:
        - 3000:3000
    environment:
        - "GRPC_SERVER_HOST=0.0.0.0"
        - "GRPC_SERVER_PORT=3000"
  gateway:
    image: "grpc-gw"
    ports:
        - 4000:4000
    environment:
        - "GRPC_SERVER_HOST=server"
        - "GRPC_SERVER_PORT=3000"
        - "GRPC_GW_HOST=0.0.0.0"
        - "GRPC_GW_PORT=4000"
    