version: '3.3'
services:
  server:
    image: "grpc-server"
    # build:
    #     context: .
    #     dockerfile: Dockerfile
    #     args:
    #         service: server
    restart: always
    ports:
        - 3000:3000
    env_file:
      - .env
  gateway:
    image: "grpc-gw"
    restart: always
    depends_on:
      - "server"
    ports:
        - 5000:5000
    environment:
        - "GRPC_SERVER_HOST=server"
        - "GRPC_SERVER_PORT=3000"
        - "GRPC_GW_HOST=0.0.0.0"
        - "GRPC_GW_PORT=5000"
    